// <auto-generated />
using DashboardApi.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DashboardApi.Migrations
{
    [DbContext(typeof(AcceleratorContext))]
    [Migration("20211129104520_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DashboardApi.Model.Accelerator", b =>
                {
                    b.Property<int>("accId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("accDescr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("accId");

                    b.ToTable("accelerators");
                });
#pragma warning restore 612, 618
        }
    }
}
